# executable files for this directory
#OBJECTS = ex1_3.exe myex1_9.exe
OBJECTS = *.cpp

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

#add_item.exe add_item2.exe avg_price.exe item_io.exe: Sales_item.h
